language: csharp

install:

 - sudo apt-get install nunit
 - sudo apt-get install libnewtonsoft-json-cil-dev  monodoc-newtonsoft-json-manual

before_script:

  - export isTravisTest=true
 
script: 

 - make build-and-test
